# Generated by Django 5.1.4 on 2025-01-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('merchant', 'Merchant'), ('customer', 'Customer')], max_length=20),
        ),
    ]
