# Generated by Django 5.1.4 on 2025-01-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_completed',
            field=models.BooleanField(default=False),
        ),
    ]
