# Generated by Django 5.1.4 on 2025-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sensitive_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
