# Generated by Django 5.1.4 on 2025-02-08 09:32

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_sensitive_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_completed',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sensitive_info',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
