# Generated by Django 5.1.4 on 2025-01-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_available_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
