# Generated by Django 5.1.4 on 2025-01-10 10:04

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=15, null=True),
        ),
    ]
