# Generated by Django 5.1.4 on 2025-02-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_transaction_id'),
        ('products', '0013_alter_product_merchant'),
    ]

    operations = [
    ]
